# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dcs.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(727, 567)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Agency FB"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        MainWindow.setMouseTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("ico/scada.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(True)
        MainWindow.setStyleSheet(_fromUtf8("QTableWidget,QTabWidget,QTextEdit{background-color:rgb(111, 111, 111);color:white;gridline-color:rgb(191, 191, 191)}\n"
"\n"
"QTabWidget{background-color:rgb(111, 111, 111);color:black}\n"
"\n"
"QTabBar::tab,QHeaderView::section{background-color:rgb(111, 111, 111);color: white}\n"
"\n"
"QTabBar::tab:selected {background-color:rgb(83, 166, 249);}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
""))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setStyleSheet(_fromUtf8("background-color: rgb(111, 111, 111);"))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget1 = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget1.setEnabled(True)
        self.tabWidget1.setGeometry(QtCore.QRect(800, 70, 578, 452))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tabWidget1.setFont(font)
        self.tabWidget1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tabWidget1.setAutoFillBackground(False)
        self.tabWidget1.setStyleSheet(_fromUtf8("background-color:#CCCCCC;"))
        self.tabWidget1.setObjectName(_fromUtf8("tabWidget1"))
        self.tab = QtGui.QWidget()
        self.tab.setAutoFillBackground(False)
        self.tab.setStyleSheet(_fromUtf8(""))
        self.tab.setObjectName(_fromUtf8("tab"))
        self.tableWidget1 = QtGui.QTableWidget(self.tab)
        self.tableWidget1.setGeometry(QtCore.QRect(0, 0, 575, 428))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tableWidget1.setFont(font)
        self.tableWidget1.setAcceptDrops(False)
        self.tableWidget1.setAutoFillBackground(False)
        self.tableWidget1.setStyleSheet(_fromUtf8("QHeaderView::section{background-color:#CCCCCC;color: black}\n"
"QTableWidget{background-color:#111111;}"))
        self.tableWidget1.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidget1.setDragEnabled(False)
        self.tableWidget1.setAlternatingRowColors(False)
        self.tableWidget1.setSelectionBehavior(QtGui.QAbstractItemView.SelectItems)
        self.tableWidget1.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget1.setRowCount(0)
        self.tableWidget1.setColumnCount(7)
        self.tableWidget1.setObjectName(_fromUtf8("tableWidget1"))
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget1.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget1.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget1.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget1.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget1.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget1.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget1.setHorizontalHeaderItem(6, item)
        self.tableWidget1.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget1.verticalHeader().setVisible(True)
        self.tableWidget1.verticalHeader().setCascadingSectionResizes(False)
        self.tabWidget1.addTab(self.tab, _fromUtf8(""))
        self.tab_11 = QtGui.QWidget()
        self.tab_11.setObjectName(_fromUtf8("tab_11"))
        self.aftableWidget = QtGui.QTableWidget(self.tab_11)
        self.aftableWidget.setGeometry(QtCore.QRect(0, 0, 575, 430))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.aftableWidget.setFont(font)
        self.aftableWidget.setStyleSheet(_fromUtf8("QHeaderView::section{background-color:#CCCCCC;color: black}\n"
"QTableWidget{background-color:#111111;}"))
        self.aftableWidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.aftableWidget.setRowCount(0)
        self.aftableWidget.setObjectName(_fromUtf8("aftableWidget"))
        self.aftableWidget.setColumnCount(7)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.aftableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.aftableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.aftableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.aftableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.aftableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.aftableWidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.aftableWidget.setHorizontalHeaderItem(6, item)
        self.tabWidget1.addTab(self.tab_11, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.wtableWidget = QtGui.QTableWidget(self.tab_2)
        self.wtableWidget.setGeometry(QtCore.QRect(0, 0, 575, 430))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.wtableWidget.setFont(font)
        self.wtableWidget.setStyleSheet(_fromUtf8("QHeaderView::section{background-color:#CCCCCC;color: black}\n"
"QTableWidget{background-color:#111111;}"))
        self.wtableWidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.wtableWidget.setRowCount(0)
        self.wtableWidget.setObjectName(_fromUtf8("wtableWidget"))
        self.wtableWidget.setColumnCount(7)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.wtableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.wtableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.wtableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.wtableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.wtableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.wtableWidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.wtableWidget.setHorizontalHeaderItem(6, item)
        self.tabWidget1.addTab(self.tab_2, _fromUtf8(""))
        self.tabWidget3 = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget3.setGeometry(QtCore.QRect(800, 70, 578, 452))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tabWidget3.setFont(font)
        self.tabWidget3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tabWidget3.setStyleSheet(_fromUtf8("background-color:#CCCCCC;"))
        self.tabWidget3.setObjectName(_fromUtf8("tabWidget3"))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.tableWidget_alarmrecord = QtGui.QTableWidget(self.tab_4)
        self.tableWidget_alarmrecord.setGeometry(QtCore.QRect(0, 0, 576, 408))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tableWidget_alarmrecord.setFont(font)
        self.tableWidget_alarmrecord.setAcceptDrops(False)
        self.tableWidget_alarmrecord.setStyleSheet(_fromUtf8("QHeaderView::section{background-color:#CCCCCC;color: black}\n"
"QTableWidget{background-color:#111111;}"))
        self.tableWidget_alarmrecord.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidget_alarmrecord.setDragEnabled(False)
        self.tableWidget_alarmrecord.setAlternatingRowColors(False)
        self.tableWidget_alarmrecord.setRowCount(0)
        self.tableWidget_alarmrecord.setColumnCount(4)
        self.tableWidget_alarmrecord.setObjectName(_fromUtf8("tableWidget_alarmrecord"))
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_alarmrecord.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_alarmrecord.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_alarmrecord.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_alarmrecord.setHorizontalHeaderItem(3, item)
        self.tableWidget_alarmrecord.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_alarmrecord.verticalHeader().setCascadingSectionResizes(False)
        self.dateEdit1 = QtGui.QDateEdit(self.tab_4)
        self.dateEdit1.setGeometry(QtCore.QRect(30, 410, 60, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dateEdit1.setFont(font)
        self.dateEdit1.setCurrentSection(QtGui.QDateTimeEdit.DaySection)
        self.dateEdit1.setCalendarPopup(True)
        self.dateEdit1.setCurrentSectionIndex(2)
        self.dateEdit1.setDate(QtCore.QDate(2011, 12, 20))
        self.dateEdit1.setObjectName(_fromUtf8("dateEdit1"))
        self.dateEdit2 = QtGui.QDateEdit(self.tab_4)
        self.dateEdit2.setGeometry(QtCore.QRect(110, 410, 60, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dateEdit2.setFont(font)
        self.dateEdit2.setCalendarPopup(True)
        self.dateEdit2.setDate(QtCore.QDate(2012, 4, 1))
        self.dateEdit2.setObjectName(_fromUtf8("dateEdit2"))
        self.label = QtGui.QLabel(self.tab_4)
        self.label.setGeometry(QtCore.QRect(10, 410, 17, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_8 = QtGui.QLabel(self.tab_4)
        self.label_8.setGeometry(QtCore.QRect(95, 410, 9, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.tab_4)
        self.label_9.setGeometry(QtCore.QRect(200, 410, 17, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.comboBox_region = QtGui.QComboBox(self.tab_4)
        self.comboBox_region.setGeometry(QtCore.QRect(222, 410, 90, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.comboBox_region.setFont(font)
        self.comboBox_region.setObjectName(_fromUtf8("comboBox_region"))
        self.comboBox_region.addItem(_fromUtf8(""))
        self.queryButton = QtGui.QPushButton(self.tab_4)
        self.queryButton.setGeometry(QtCore.QRect(460, 410, 45, 23))
        self.queryButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.queryButton.setObjectName(_fromUtf8("queryButton"))
        self.export_drecord_Button = QtGui.QPushButton(self.tab_4)
        self.export_drecord_Button.setGeometry(QtCore.QRect(520, 410, 45, 23))
        self.export_drecord_Button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.export_drecord_Button.setObjectName(_fromUtf8("export_drecord_Button"))
        self.comboBox_ctrller = QtGui.QComboBox(self.tab_4)
        self.comboBox_ctrller.setGeometry(QtCore.QRect(360, 410, 60, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.comboBox_ctrller.setFont(font)
        self.comboBox_ctrller.setObjectName(_fromUtf8("comboBox_ctrller"))
        self.comboBox_ctrller.addItem(_fromUtf8(""))
        self.label_14 = QtGui.QLabel(self.tab_4)
        self.label_14.setGeometry(QtCore.QRect(333, 410, 27, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.tabWidget3.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.tableWidget_walarmrecord = QtGui.QTableWidget(self.tab_5)
        self.tableWidget_walarmrecord.setGeometry(QtCore.QRect(0, 0, 576, 408))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tableWidget_walarmrecord.setFont(font)
        self.tableWidget_walarmrecord.setStyleSheet(_fromUtf8("QHeaderView::section{background-color:#CCCCCC;color: black}\n"
"QTableWidget{background-color:#111111;}"))
        self.tableWidget_walarmrecord.setRowCount(0)
        self.tableWidget_walarmrecord.setObjectName(_fromUtf8("tableWidget_walarmrecord"))
        self.tableWidget_walarmrecord.setColumnCount(6)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_walarmrecord.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_walarmrecord.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_walarmrecord.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_walarmrecord.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_walarmrecord.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_walarmrecord.setHorizontalHeaderItem(5, item)
        self.label_10 = QtGui.QLabel(self.tab_5)
        self.label_10.setGeometry(QtCore.QRect(163, 410, 17, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.tab_5)
        self.label_11.setGeometry(QtCore.QRect(77, 410, 9, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.wqueryButton = QtGui.QPushButton(self.tab_5)
        self.wqueryButton.setGeometry(QtCore.QRect(480, 410, 40, 23))
        self.wqueryButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.wqueryButton.setObjectName(_fromUtf8("wqueryButton"))
        self.wcomboBox_region = QtGui.QComboBox(self.tab_5)
        self.wcomboBox_region.setGeometry(QtCore.QRect(183, 410, 60, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.wcomboBox_region.setFont(font)
        self.wcomboBox_region.setObjectName(_fromUtf8("wcomboBox_region"))
        self.label_12 = QtGui.QLabel(self.tab_5)
        self.label_12.setGeometry(QtCore.QRect(5, 410, 17, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.wdateEdit1 = QtGui.QDateEdit(self.tab_5)
        self.wdateEdit1.setGeometry(QtCore.QRect(23, 410, 50, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.wdateEdit1.setFont(font)
        self.wdateEdit1.setCurrentSection(QtGui.QDateTimeEdit.DaySection)
        self.wdateEdit1.setCalendarPopup(True)
        self.wdateEdit1.setCurrentSectionIndex(2)
        self.wdateEdit1.setDate(QtCore.QDate(2011, 12, 20))
        self.wdateEdit1.setObjectName(_fromUtf8("wdateEdit1"))
        self.wdateEdit2 = QtGui.QDateEdit(self.tab_5)
        self.wdateEdit2.setGeometry(QtCore.QRect(90, 410, 50, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.wdateEdit2.setFont(font)
        self.wdateEdit2.setCalendarPopup(True)
        self.wdateEdit2.setDate(QtCore.QDate(2012, 4, 1))
        self.wdateEdit2.setObjectName(_fromUtf8("wdateEdit2"))
        self.export_crecord_Button = QtGui.QPushButton(self.tab_5)
        self.export_crecord_Button.setGeometry(QtCore.QRect(530, 410, 40, 23))
        self.export_crecord_Button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.export_crecord_Button.setObjectName(_fromUtf8("export_crecord_Button"))
        self.wcomboBox_ctrller = QtGui.QComboBox(self.tab_5)
        self.wcomboBox_ctrller.setGeometry(QtCore.QRect(291, 410, 40, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.wcomboBox_ctrller.setFont(font)
        self.wcomboBox_ctrller.setObjectName(_fromUtf8("wcomboBox_ctrller"))
        self.label_16 = QtGui.QLabel(self.tab_5)
        self.label_16.setGeometry(QtCore.QRect(256, 410, 26, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.wcomboBox_dev = QtGui.QComboBox(self.tab_5)
        self.wcomboBox_dev.setGeometry(QtCore.QRect(380, 410, 70, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.wcomboBox_dev.setFont(font)
        self.wcomboBox_dev.setObjectName(_fromUtf8("wcomboBox_dev"))
        self.label_19 = QtGui.QLabel(self.tab_5)
        self.label_19.setGeometry(QtCore.QRect(343, 410, 34, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.tabWidget3.addTab(self.tab_5, _fromUtf8(""))
        self.tab_concentration = QtGui.QWidget()
        self.tab_concentration.setObjectName(_fromUtf8("tab_concentration"))
        self.label_3 = QtGui.QLabel(self.tab_concentration)
        self.label_3.setGeometry(QtCore.QRect(10, 410, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_27 = QtGui.QLabel(self.tab_concentration)
        self.label_27.setGeometry(QtCore.QRect(210, 410, 28, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_27.setFont(font)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.tableWidget_concttrecord = QtGui.QTableWidget(self.tab_concentration)
        self.tableWidget_concttrecord.setGeometry(QtCore.QRect(0, 0, 576, 408))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tableWidget_concttrecord.setFont(font)
        self.tableWidget_concttrecord.setAcceptDrops(False)
        self.tableWidget_concttrecord.setStyleSheet(_fromUtf8("QHeaderView::section{background-color:#CCCCCC;color: black}\n"
"QTableWidget{background-color:#111111;}"))
        self.tableWidget_concttrecord.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidget_concttrecord.setDragEnabled(False)
        self.tableWidget_concttrecord.setAlternatingRowColors(False)
        self.tableWidget_concttrecord.setRowCount(0)
        self.tableWidget_concttrecord.setColumnCount(7)
        self.tableWidget_concttrecord.setObjectName(_fromUtf8("tableWidget_concttrecord"))
        item = QtGui.QTableWidgetItem()
        self.tableWidget_concttrecord.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_concttrecord.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_concttrecord.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_concttrecord.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_concttrecord.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_concttrecord.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_concttrecord.setHorizontalHeaderItem(6, item)
        self.tableWidget_concttrecord.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_concttrecord.verticalHeader().setCascadingSectionResizes(False)
        self.queryButton_conctt = QtGui.QPushButton(self.tab_concentration)
        self.queryButton_conctt.setGeometry(QtCore.QRect(440, 410, 60, 23))
        self.queryButton_conctt.setFocusPolicy(QtCore.Qt.NoFocus)
        self.queryButton_conctt.setObjectName(_fromUtf8("queryButton_conctt"))
        self.dateEdit_conctt_2 = QtGui.QDateEdit(self.tab_concentration)
        self.dateEdit_conctt_2.setGeometry(QtCore.QRect(120, 410, 60, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dateEdit_conctt_2.setFont(font)
        self.dateEdit_conctt_2.setCalendarPopup(True)
        self.dateEdit_conctt_2.setDate(QtCore.QDate(2012, 4, 1))
        self.dateEdit_conctt_2.setObjectName(_fromUtf8("dateEdit_conctt_2"))
        self.dateEdit_conctt_1 = QtGui.QDateEdit(self.tab_concentration)
        self.dateEdit_conctt_1.setGeometry(QtCore.QRect(40, 410, 60, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dateEdit_conctt_1.setFont(font)
        self.dateEdit_conctt_1.setCurrentSection(QtGui.QDateTimeEdit.DaySection)
        self.dateEdit_conctt_1.setCalendarPopup(True)
        self.dateEdit_conctt_1.setCurrentSectionIndex(2)
        self.dateEdit_conctt_1.setDate(QtCore.QDate(2011, 12, 20))
        self.dateEdit_conctt_1.setObjectName(_fromUtf8("dateEdit_conctt_1"))
        self.comboBox_conctt_ctrller = QtGui.QComboBox(self.tab_concentration)
        self.comboBox_conctt_ctrller.setGeometry(QtCore.QRect(239, 410, 40, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.comboBox_conctt_ctrller.setFont(font)
        self.comboBox_conctt_ctrller.setObjectName(_fromUtf8("comboBox_conctt_ctrller"))
        self.comboBox_conctt_ctrller.addItem(_fromUtf8(""))
        self.label_28 = QtGui.QLabel(self.tab_concentration)
        self.label_28.setGeometry(QtCore.QRect(106, 410, 10, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_28.setFont(font)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.export_hrecord_Button = QtGui.QPushButton(self.tab_concentration)
        self.export_hrecord_Button.setGeometry(QtCore.QRect(505, 410, 60, 23))
        self.export_hrecord_Button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.export_hrecord_Button.setObjectName(_fromUtf8("export_hrecord_Button"))
        self.comboBox_conctt_detector = QtGui.QComboBox(self.tab_concentration)
        self.comboBox_conctt_detector.setGeometry(QtCore.QRect(337, 410, 80, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.comboBox_conctt_detector.setFont(font)
        self.comboBox_conctt_detector.setObjectName(_fromUtf8("comboBox_conctt_detector"))
        self.comboBox_conctt_detector.addItem(_fromUtf8(""))
        self.label_29 = QtGui.QLabel(self.tab_concentration)
        self.label_29.setGeometry(QtCore.QRect(300, 410, 34, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_29.setFont(font)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.tabWidget3.addTab(self.tab_concentration, _fromUtf8(""))
        self.tabWidget2 = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget2.setGeometry(QtCore.QRect(800, 70, 578, 452))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tabWidget2.setFont(font)
        self.tabWidget2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tabWidget2.setStyleSheet(_fromUtf8("background-color:#CCCCCC"))
        self.tabWidget2.setObjectName(_fromUtf8("tabWidget2"))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.tableWidget2_1 = QtGui.QTableWidget(self.tab_7)
        self.tableWidget2_1.setGeometry(QtCore.QRect(0, 0, 575, 408))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tableWidget2_1.setFont(font)
        self.tableWidget2_1.setAcceptDrops(False)
        self.tableWidget2_1.setStyleSheet(_fromUtf8("QHeaderView::section{background-color:#CCCCCC;color: black}\n"
"QTableWidget{background-color:#111111;}"))
        self.tableWidget2_1.setEditTriggers(QtGui.QAbstractItemView.DoubleClicked)
        self.tableWidget2_1.setDragEnabled(False)
        self.tableWidget2_1.setAlternatingRowColors(False)
        self.tableWidget2_1.setRowCount(0)
        self.tableWidget2_1.setColumnCount(8)
        self.tableWidget2_1.setObjectName(_fromUtf8("tableWidget2_1"))
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget2_1.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget2_1.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget2_1.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget2_1.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget2_1.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget2_1.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget2_1.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget2_1.setHorizontalHeaderItem(7, item)
        self.tableWidget2_1.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget2_1.verticalHeader().setCascadingSectionResizes(False)
        self.addButton = QtGui.QPushButton(self.tab_7)
        self.addButton.setGeometry(QtCore.QRect(30, 410, 70, 23))
        self.addButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.addButton.setObjectName(_fromUtf8("addButton"))
        self.delButton = QtGui.QPushButton(self.tab_7)
        self.delButton.setGeometry(QtCore.QRect(140, 410, 70, 23))
        self.delButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.delButton.setObjectName(_fromUtf8("delButton"))
        self.editButton = QtGui.QPushButton(self.tab_7)
        self.editButton.setGeometry(QtCore.QRect(240, 410, 70, 23))
        self.editButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.editButton.setObjectName(_fromUtf8("editButton"))
        self.lineEdit = QtGui.QLineEdit(self.tab_7)
        self.lineEdit.setGeometry(QtCore.QRect(100, 410, 31, 20))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.exportdtctButton = QtGui.QPushButton(self.tab_7)
        self.exportdtctButton.setGeometry(QtCore.QRect(490, 410, 70, 23))
        self.exportdtctButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.exportdtctButton.setObjectName(_fromUtf8("exportdtctButton"))
        self.importdtctButton = QtGui.QPushButton(self.tab_7)
        self.importdtctButton.setGeometry(QtCore.QRect(410, 410, 70, 23))
        self.importdtctButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.importdtctButton.setObjectName(_fromUtf8("importdtctButton"))
        self.tabWidget2.addTab(self.tab_7, _fromUtf8(""))
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName(_fromUtf8("tab_8"))
        self.winfotableWidget = QtGui.QTableWidget(self.tab_8)
        self.winfotableWidget.setGeometry(QtCore.QRect(0, 0, 575, 408))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.winfotableWidget.setFont(font)
        self.winfotableWidget.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.winfotableWidget.setStyleSheet(_fromUtf8("QHeaderView::section{background-color:#CCCCCC;color: black}\n"
"QTableWidget{background-color:#111111;}"))
        self.winfotableWidget.setRowCount(0)
        self.winfotableWidget.setObjectName(_fromUtf8("winfotableWidget"))
        self.winfotableWidget.setColumnCount(7)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.winfotableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.winfotableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.winfotableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.winfotableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.winfotableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.winfotableWidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.winfotableWidget.setHorizontalHeaderItem(6, item)
        self.wlineEdit = QtGui.QLineEdit(self.tab_8)
        self.wlineEdit.setGeometry(QtCore.QRect(90, 410, 31, 20))
        self.wlineEdit.setObjectName(_fromUtf8("wlineEdit"))
        self.waddButton = QtGui.QPushButton(self.tab_8)
        self.waddButton.setGeometry(QtCore.QRect(20, 410, 70, 23))
        self.waddButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.waddButton.setObjectName(_fromUtf8("waddButton"))
        self.wdelButton = QtGui.QPushButton(self.tab_8)
        self.wdelButton.setGeometry(QtCore.QRect(130, 410, 70, 23))
        self.wdelButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.wdelButton.setObjectName(_fromUtf8("wdelButton"))
        self.weditButton = QtGui.QPushButton(self.tab_8)
        self.weditButton.setGeometry(QtCore.QRect(210, 410, 70, 23))
        self.weditButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.weditButton.setObjectName(_fromUtf8("weditButton"))
        self.exportexctrlButton = QtGui.QPushButton(self.tab_8)
        self.exportexctrlButton.setGeometry(QtCore.QRect(490, 410, 70, 23))
        self.exportexctrlButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.exportexctrlButton.setObjectName(_fromUtf8("exportexctrlButton"))
        self.importexctrlButton = QtGui.QPushButton(self.tab_8)
        self.importexctrlButton.setGeometry(QtCore.QRect(410, 410, 70, 23))
        self.importexctrlButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.importexctrlButton.setObjectName(_fromUtf8("importexctrlButton"))
        self.readButton = QtGui.QPushButton(self.tab_8)
        self.readButton.setGeometry(QtCore.QRect(330, 410, 70, 23))
        self.readButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.readButton.setObjectName(_fromUtf8("readButton"))
        self.tabWidget2.addTab(self.tab_8, _fromUtf8(""))
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(800, 60, 588, 469))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.widget.setFont(font)
        self.widget.setStyleSheet(_fromUtf8("QPushButton {\n"
"border: 1px solid rgb(185, 185, 185);\n"
"border-radius: 1px;\n"
"padding: 0px;\n"
"}\n"
"QPushButton:hover{background-color:rgb(180, 180, 180);}\n"
"QPushButton:pressed {\n"
"background: qradialgradient(cx: 0.4, cy: -0.1,\n"
"fx: 0.4, fy: -0.1,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #ddd);\n"
"}\n"
"\n"
"QComboBox {border:1px solid #000000}"))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.groupBox = QtGui.QGroupBox(self.widget)
        self.groupBox.setGeometry(QtCore.QRect(70, 10, 181, 217))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label_13 = QtGui.QLabel(self.groupBox)
        self.label_13.setGeometry(QtCore.QRect(20, 20, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.comcomboBox = QtGui.QComboBox(self.groupBox)
        self.comcomboBox.setGeometry(QtCore.QRect(100, 20, 51, 20))
        self.comcomboBox.setObjectName(_fromUtf8("comcomboBox"))
        self.comcomboBox.addItem(_fromUtf8(""))
        self.comcomboBox.addItem(_fromUtf8(""))
        self.comcomboBox.addItem(_fromUtf8(""))
        self.comcomboBox.addItem(_fromUtf8(""))
        self.serialButton = QtGui.QPushButton(self.groupBox)
        self.serialButton.setGeometry(QtCore.QRect(94, 47, 61, 23))
        self.serialButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.serialButton.setObjectName(_fromUtf8("serialButton"))
        self.smscomboBox = QtGui.QComboBox(self.groupBox)
        self.smscomboBox.setGeometry(QtCore.QRect(100, 85, 51, 20))
        self.smscomboBox.setObjectName(_fromUtf8("smscomboBox"))
        self.smscomboBox.addItem(_fromUtf8(""))
        self.smscomboBox.addItem(_fromUtf8(""))
        self.smscomboBox.addItem(_fromUtf8(""))
        self.smscomboBox.addItem(_fromUtf8(""))
        self.label_15 = QtGui.QLabel(self.groupBox)
        self.label_15.setGeometry(QtCore.QRect(20, 85, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.smscomButton = QtGui.QPushButton(self.groupBox)
        self.smscomButton.setGeometry(QtCore.QRect(94, 115, 61, 23))
        self.smscomButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.smscomButton.setObjectName(_fromUtf8("smscomButton"))
        self.output_label = QtGui.QLabel(self.groupBox)
        self.output_label.setGeometry(QtCore.QRect(20, 150, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.output_label.setFont(font)
        self.output_label.setObjectName(_fromUtf8("output_label"))
        self.outputcomButton = QtGui.QPushButton(self.groupBox)
        self.outputcomButton.setGeometry(QtCore.QRect(94, 180, 61, 23))
        self.outputcomButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.outputcomButton.setObjectName(_fromUtf8("outputcomButton"))
        self.outputcomboBox = QtGui.QComboBox(self.groupBox)
        self.outputcomboBox.setGeometry(QtCore.QRect(100, 150, 51, 20))
        self.outputcomboBox.setObjectName(_fromUtf8("outputcomboBox"))
        self.outputcomboBox.addItem(_fromUtf8(""))
        self.outputcomboBox.addItem(_fromUtf8(""))
        self.outputcomboBox.addItem(_fromUtf8(""))
        self.outputcomboBox.addItem(_fromUtf8(""))
        self.groupBox_3 = QtGui.QGroupBox(self.widget)
        self.groupBox_3.setGeometry(QtCore.QRect(330, 10, 181, 201))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.label_17 = QtGui.QLabel(self.groupBox_3)
        self.label_17.setGeometry(QtCore.QRect(10, 20, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_18 = QtGui.QLabel(self.groupBox_3)
        self.label_18.setGeometry(QtCore.QRect(10, 50, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.lineEdit_username = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_username.setGeometry(QtCore.QRect(90, 20, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_username.setFont(font)
        self.lineEdit_username.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_username.setReadOnly(True)
        self.lineEdit_username.setObjectName(_fromUtf8("lineEdit_username"))
        self.lineEdit_Num_1 = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_Num_1.setGeometry(QtCore.QRect(90, 50, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_Num_1.setFont(font)
        self.lineEdit_Num_1.setText(_fromUtf8(""))
        self.lineEdit_Num_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Num_1.setReadOnly(True)
        self.lineEdit_Num_1.setObjectName(_fromUtf8("lineEdit_Num_1"))
        self.smssaveButton = QtGui.QPushButton(self.groupBox_3)
        self.smssaveButton.setGeometry(QtCore.QRect(95, 170, 75, 23))
        self.smssaveButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.smssaveButton.setObjectName(_fromUtf8("smssaveButton"))
        self.smseditButton = QtGui.QPushButton(self.groupBox_3)
        self.smseditButton.setGeometry(QtCore.QRect(10, 170, 75, 23))
        self.smseditButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.smseditButton.setObjectName(_fromUtf8("smseditButton"))
        self.groupBox_4 = QtGui.QGroupBox(self.widget)
        self.groupBox_4.setGeometry(QtCore.QRect(70, 240, 181, 201))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.label_39 = QtGui.QLabel(self.groupBox_4)
        self.label_39.setGeometry(QtCore.QRect(10, 20, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_39.setFont(font)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.label_40 = QtGui.QLabel(self.groupBox_4)
        self.label_40.setGeometry(QtCore.QRect(10, 50, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_40.setFont(font)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.lineEdit_current_psw = QtGui.QLineEdit(self.groupBox_4)
        self.lineEdit_current_psw.setGeometry(QtCore.QRect(90, 20, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_current_psw.setFont(font)
        self.lineEdit_current_psw.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_current_psw.setReadOnly(True)
        self.lineEdit_current_psw.setObjectName(_fromUtf8("lineEdit_current_psw"))
        self.lineEdit_new_psw = QtGui.QLineEdit(self.groupBox_4)
        self.lineEdit_new_psw.setGeometry(QtCore.QRect(90, 50, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_new_psw.setFont(font)
        self.lineEdit_new_psw.setText(_fromUtf8(""))
        self.lineEdit_new_psw.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_new_psw.setReadOnly(True)
        self.lineEdit_new_psw.setObjectName(_fromUtf8("lineEdit_new_psw"))
        self.lineEdit_confirm_psw = QtGui.QLineEdit(self.groupBox_4)
        self.lineEdit_confirm_psw.setGeometry(QtCore.QRect(90, 80, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_confirm_psw.setFont(font)
        self.lineEdit_confirm_psw.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_confirm_psw.setReadOnly(True)
        self.lineEdit_confirm_psw.setObjectName(_fromUtf8("lineEdit_confirm_psw"))
        self.label_41 = QtGui.QLabel(self.groupBox_4)
        self.label_41.setGeometry(QtCore.QRect(10, 80, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_41.setFont(font)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.confirm_modify_Button = QtGui.QPushButton(self.groupBox_4)
        self.confirm_modify_Button.setGeometry(QtCore.QRect(95, 170, 75, 23))
        self.confirm_modify_Button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.confirm_modify_Button.setObjectName(_fromUtf8("confirm_modify_Button"))
        self.modify_psw_Button = QtGui.QPushButton(self.groupBox_4)
        self.modify_psw_Button.setGeometry(QtCore.QRect(10, 170, 75, 23))
        self.modify_psw_Button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.modify_psw_Button.setObjectName(_fromUtf8("modify_psw_Button"))
        self.headlabel = QtGui.QLabel(self.centralwidget)
        self.headlabel.setGeometry(QtCore.QRect(0, 0, 728, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Agency FB"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.headlabel.setFont(font)
        self.headlabel.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(220, 220, 220, 220), stop:1 rgba(140, 140, 140, 140));\n"
"color: rgb(255, 255, 255);\n"
""))
        self.headlabel.setTextFormat(QtCore.Qt.AutoText)
        self.headlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.headlabel.setObjectName(_fromUtf8("headlabel"))
        self.widget_5 = QtGui.QWidget(self.centralwidget)
        self.widget_5.setGeometry(QtCore.QRect(0, 60, 140, 473))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Agency FB"))
        font.setPointSize(10)
        self.widget_5.setFont(font)
        self.widget_5.setStyleSheet(_fromUtf8("background-color: rgb(111, 111, 111);"))
        self.widget_5.setObjectName(_fromUtf8("widget_5"))
        self.pushButton = QtGui.QPushButton(self.widget_5)
        self.pushButton.setGeometry(QtCore.QRect(131, 5, 3, 458))
        self.pushButton.setStyleSheet(_fromUtf8("background-color: rgb(90, 90, 90);"))
        self.pushButton.setText(_fromUtf8(""))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton_2 = QtGui.QPushButton(self.widget_5)
        self.pushButton_2.setGeometry(QtCore.QRect(8, 462, 126, 3))
        self.pushButton_2.setStyleSheet(_fromUtf8("background-color: rgb(90, 90, 90);"))
        self.pushButton_2.setText(_fromUtf8(""))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.pushButton_3 = QtGui.QPushButton(self.widget_5)
        self.pushButton_3.setGeometry(QtCore.QRect(7, 5, 2, 459))
        self.pushButton_3.setStyleSheet(_fromUtf8("background-color: rgb(235, 235, 235);"))
        self.pushButton_3.setText(_fromUtf8(""))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.pushButton_4 = QtGui.QPushButton(self.widget_5)
        self.pushButton_4.setGeometry(QtCore.QRect(7, 5, 127, 2))
        self.pushButton_4.setStyleSheet(_fromUtf8("background-color: rgb(235, 235, 235);"))
        self.pushButton_4.setText(_fromUtf8(""))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.widget_4 = QtGui.QWidget(self.widget_5)
        self.widget_4.setGeometry(QtCore.QRect(8, 6, 125, 458))
        self.widget_4.setObjectName(_fromUtf8("widget_4"))
        self.label_4 = QtGui.QLabel(self.widget_4)
        self.label_4.setGeometry(QtCore.QRect(25, 2, 81, 19))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Agency FB"))
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet(_fromUtf8("color: rgb(252, 252, 252);"))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.textBrowser = QtGui.QTextBrowser(self.widget_4)
        self.textBrowser.setGeometry(QtCore.QRect(4, 23, 117, 431))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet(_fromUtf8("background-color: rgb(129, 129, 129);"))
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.pushButton_6 = QtGui.QPushButton(self.widget_5)
        self.pushButton_6.setGeometry(QtCore.QRect(139, 6, 2, 459))
        self.pushButton_6.setStyleSheet(_fromUtf8("background-color: rgb(235, 235, 235);"))
        self.pushButton_6.setText(_fromUtf8(""))
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.widget_2 = QtGui.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(0, 25, 728, 35))
        self.widget_2.setStyleSheet(_fromUtf8("background-color: rgb(200, 200, 200);"))
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.mainuiButton = QtGui.QPushButton(self.widget_2)
        self.mainuiButton.setEnabled(True)
        self.mainuiButton.setGeometry(QtCore.QRect(144, 0, 70, 35))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainuiButton.sizePolicy().hasHeightForWidth())
        self.mainuiButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Agency FB"))
        font.setPointSize(11)
        font.setKerning(True)
        self.mainuiButton.setFont(font)
        self.mainuiButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.mainuiButton.setStyleSheet(_fromUtf8("QPushButton {\n"
"border: 1px solid rgb(200, 200, 200);\n"
"border-right-color: rgb(189, 181, 119);\n"
"border-left-color: rgb(230, 230, 230);\n"
"padding: 0px;\n"
"}\n"
"QPushButton:hover{background-color:rgb(220, 220, 220);}\n"
"QPushButton:pressed {\n"
"background: qradialgradient(cx: 0.4, cy: -0.1,\n"
"fx: 0.4, fy: -0.1,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #ddd);\n"
"}\n"
""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("ico/monitoring.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mainuiButton.setIcon(icon1)
        self.mainuiButton.setIconSize(QtCore.QSize(32, 32))
        self.mainuiButton.setFlat(False)
        self.mainuiButton.setObjectName(_fromUtf8("mainuiButton"))
        self.alarmquButton = QtGui.QPushButton(self.widget_2)
        self.alarmquButton.setGeometry(QtCore.QRect(216, 0, 70, 35))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alarmquButton.sizePolicy().hasHeightForWidth())
        self.alarmquButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Agency FB"))
        font.setPointSize(11)
        font.setKerning(True)
        self.alarmquButton.setFont(font)
        self.alarmquButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.alarmquButton.setStyleSheet(_fromUtf8("QPushButton {\n"
"border: 1px solid rgb(200, 200, 200);\n"
"border-right-color: rgb(189, 181, 119);\n"
"border-left-color: rgb(230, 230, 230);\n"
"padding: 0px;\n"
"}\n"
"QPushButton:hover{background-color:rgb(220, 220, 220);}\n"
"QPushButton:pressed {\n"
"background: qradialgradient(cx: 0.4, cy: -0.1,\n"
"fx: 0.4, fy: -0.1,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #ddd);\n"
"}"))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("ico/query.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.alarmquButton.setIcon(icon2)
        self.alarmquButton.setIconSize(QtCore.QSize(32, 32))
        self.alarmquButton.setObjectName(_fromUtf8("alarmquButton"))
        self.exitButton = QtGui.QPushButton(self.widget_2)
        self.exitButton.setGeometry(QtCore.QRect(504, 0, 70, 35))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Agency FB"))
        font.setPointSize(11)
        self.exitButton.setFont(font)
        self.exitButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.exitButton.setStyleSheet(_fromUtf8("QPushButton {\n"
"border: 1px solid rgb(200, 200, 200);\n"
"border-left-color: rgb(230, 230, 230);\n"
"padding: 0px;\n"
"}\n"
"QPushButton:hover{background-color:rgb(220, 220, 220);}\n"
"QPushButton:pressed {\n"
"background: qradialgradient(cx: 0.4, cy: -0.1,\n"
"fx: 0.4, fy: -0.1,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #ddd);\n"
"}"))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("ico/exit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exitButton.setIcon(icon3)
        self.exitButton.setIconSize(QtCore.QSize(32, 32))
        self.exitButton.setAutoRepeat(False)
        self.exitButton.setObjectName(_fromUtf8("exitButton"))
        self.deinfoButton = QtGui.QPushButton(self.widget_2)
        self.deinfoButton.setGeometry(QtCore.QRect(72, 0, 70, 35))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deinfoButton.sizePolicy().hasHeightForWidth())
        self.deinfoButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Agency FB"))
        font.setPointSize(11)
        self.deinfoButton.setFont(font)
        self.deinfoButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.deinfoButton.setStyleSheet(_fromUtf8("QPushButton {\n"
"border: 1px solid rgb(200, 200, 200);\n"
"border-right-color: rgb(189, 181, 119);\n"
"border-left-color: rgb(230, 230, 230);\n"
"padding: 0px;\n"
"}\n"
"QPushButton:hover{background-color:rgb(220, 220, 220);}\n"
"QPushButton:pressed {\n"
"background: qradialgradient(cx: 0.4, cy: -0.1,\n"
"fx: 0.4, fy: -0.1,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #ddd);\n"
"}"))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("ico/edit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deinfoButton.setIcon(icon4)
        self.deinfoButton.setIconSize(QtCore.QSize(32, 32))
        self.deinfoButton.setObjectName(_fromUtf8("deinfoButton"))
        self.controlButton = QtGui.QPushButton(self.widget_2)
        self.controlButton.setGeometry(QtCore.QRect(0, 0, 70, 35))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.controlButton.sizePolicy().hasHeightForWidth())
        self.controlButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Agency FB"))
        font.setPointSize(11)
        self.controlButton.setFont(font)
        self.controlButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.controlButton.setStyleSheet(_fromUtf8("QPushButton {\n"
"border: 1px solid rgb(200, 200, 200);\n"
"border-right-color: rgb(189, 181, 119);\n"
"padding: 0px;\n"
"}\n"
"QPushButton:hover{background-color:rgb(220, 220, 220);}\n"
"QPushButton:pressed {\n"
"background: qradialgradient(cx: 0.4, cy: -0.1,\n"
"fx: 0.4, fy: -0.1,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #ddd);\n"
"}"))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("ico/settings.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.controlButton.setIcon(icon5)
        self.controlButton.setIconSize(QtCore.QSize(32, 32))
        self.controlButton.setObjectName(_fromUtf8("controlButton"))
        self.port_led_Button = QtGui.QToolButton(self.widget_2)
        self.port_led_Button.setGeometry(QtCore.QRect(595, 0, 30, 35))
        self.port_led_Button.setStyleSheet(_fromUtf8("border:0px;"))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("ico/gray_led.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.port_led_Button.setIcon(icon6)
        self.port_led_Button.setIconSize(QtCore.QSize(24, 24))
        self.port_led_Button.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.port_led_Button.setObjectName(_fromUtf8("port_led_Button"))
        self.fault_led_Button = QtGui.QToolButton(self.widget_2)
        self.fault_led_Button.setGeometry(QtCore.QRect(685, 0, 30, 35))
        self.fault_led_Button.setStyleSheet(_fromUtf8("border:0px;"))
        self.fault_led_Button.setIcon(icon6)
        self.fault_led_Button.setIconSize(QtCore.QSize(24, 24))
        self.fault_led_Button.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.fault_led_Button.setObjectName(_fromUtf8("fault_led_Button"))
        self.alarm_led_Button = QtGui.QToolButton(self.widget_2)
        self.alarm_led_Button.setGeometry(QtCore.QRect(655, 0, 30, 35))
        self.alarm_led_Button.setStyleSheet(_fromUtf8("border:0px;"))
        self.alarm_led_Button.setIcon(icon6)
        self.alarm_led_Button.setIconSize(QtCore.QSize(24, 24))
        self.alarm_led_Button.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.alarm_led_Button.setObjectName(_fromUtf8("alarm_led_Button"))
        self.startButton = QtGui.QPushButton(self.widget_2)
        self.startButton.setGeometry(QtCore.QRect(288, 0, 70, 35))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startButton.sizePolicy().hasHeightForWidth())
        self.startButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Agency FB"))
        font.setPointSize(11)
        self.startButton.setFont(font)
        self.startButton.setMouseTracking(False)
        self.startButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.startButton.setStyleSheet(_fromUtf8("QPushButton {\n"
"border: 1px solid rgb(200, 200, 200);\n"
"border-right-color: rgb(189, 181, 119);\n"
"border-left-color: rgb(230, 230, 230);\n"
"padding: 0px;\n"
"}\n"
"QPushButton:hover{background-color:rgb(220, 220, 220);}\n"
"QPushButton:pressed {\n"
"background: qradialgradient(cx: 0.4, cy: -0.1,\n"
"fx: 0.4, fy: -0.1,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #ddd);\n"
"}"))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("ico/run.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.startButton.setIcon(icon7)
        self.startButton.setIconSize(QtCore.QSize(32, 32))
        self.startButton.setObjectName(_fromUtf8("startButton"))
        self.resetButton = QtGui.QPushButton(self.widget_2)
        self.resetButton.setGeometry(QtCore.QRect(360, 0, 70, 35))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resetButton.sizePolicy().hasHeightForWidth())
        self.resetButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Agency FB"))
        font.setPointSize(11)
        self.resetButton.setFont(font)
        self.resetButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.resetButton.setStyleSheet(_fromUtf8("QPushButton {\n"
"border: 1px solid rgb(200, 200, 200);\n"
"border-right-color: rgb(189, 181, 119);\n"
"border-left-color: rgb(230, 230, 230);\n"
"padding: 0px;\n"
"}\n"
"QPushButton:hover{background-color:rgb(220, 220, 220);}\n"
"QPushButton:pressed {\n"
"background: qradialgradient(cx: 0.4, cy: -0.1,\n"
"fx: 0.4, fy: -0.1,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #ddd);\n"
"}"))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8("ico/reset.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.resetButton.setIcon(icon8)
        self.resetButton.setIconSize(QtCore.QSize(32, 32))
        self.resetButton.setObjectName(_fromUtf8("resetButton"))
        self.bequietButton = QtGui.QPushButton(self.widget_2)
        self.bequietButton.setGeometry(QtCore.QRect(432, 0, 70, 35))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bequietButton.sizePolicy().hasHeightForWidth())
        self.bequietButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Agency FB"))
        font.setPointSize(11)
        self.bequietButton.setFont(font)
        self.bequietButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bequietButton.setStyleSheet(_fromUtf8("QPushButton {\n"
"border: 1px solid rgb(200, 200, 200);\n"
"border-right-color: rgb(189, 181, 119);\n"
"border-left-color: rgb(230, 230, 230);\n"
"padding: 0px;\n"
"}\n"
"QPushButton:hover{background-color:rgb(220, 220, 220);}\n"
"QPushButton:pressed {\n"
"background: qradialgradient(cx: 0.4, cy: -0.1,\n"
"fx: 0.4, fy: -0.1,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #ddd);\n"
"}"))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8("ico/erasure.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bequietButton.setIcon(icon9)
        self.bequietButton.setIconSize(QtCore.QSize(32, 32))
        self.bequietButton.setObjectName(_fromUtf8("bequietButton"))
        self.shield_led_Button = QtGui.QToolButton(self.widget_2)
        self.shield_led_Button.setGeometry(QtCore.QRect(625, 0, 30, 35))
        self.shield_led_Button.setStyleSheet(_fromUtf8("border:0px;"))
        self.shield_led_Button.setIcon(icon6)
        self.shield_led_Button.setIconSize(QtCore.QSize(24, 24))
        self.shield_led_Button.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.shield_led_Button.setObjectName(_fromUtf8("shield_led_Button"))
        self.pushButton_5 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(0, 528, 727, 3))
        self.pushButton_5.setStyleSheet(_fromUtf8("background-color: rgb(98, 98, 98);"))
        self.pushButton_5.setText(_fromUtf8(""))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.pushButton_7 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(139, 65, 581, 3))
        self.pushButton_7.setStyleSheet(_fromUtf8("background-color: rgb(235, 235, 235);"))
        self.pushButton_7.setText(_fromUtf8(""))
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.pushButton_8 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(718, 66, 3, 459))
        self.pushButton_8.setStyleSheet(_fromUtf8("background-color: rgb(98, 98, 98);"))
        self.pushButton_8.setText(_fromUtf8(""))
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.pushButton_9 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(140, 522, 580, 3))
        self.pushButton_9.setStyleSheet(_fromUtf8("background-color: rgb(98, 98, 98);"))
        self.pushButton_9.setText(_fromUtf8(""))
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.statusBar.setFont(font)
        self.statusBar.setStyleSheet(_fromUtf8("background-color: rgb(161, 161, 161);"))
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.comset = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.comset.setFont(font)
        self.comset.setObjectName(_fromUtf8("comset"))
        self.action_2 = QtGui.QAction(MainWindow)
        self.action_2.setObjectName(_fromUtf8("action_2"))
        self.exit = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.exit.setFont(font)
        self.exit.setObjectName(_fromUtf8("exit"))
        self.action_7 = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.action_7.setFont(font)
        self.action_7.setObjectName(_fromUtf8("action_7"))
        self.action_8 = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.action_8.setFont(font)
        self.action_8.setObjectName(_fromUtf8("action_8"))
        self.add_detector = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.add_detector.setFont(font)
        self.add_detector.setObjectName(_fromUtf8("add_detector"))
        self.modify_detector = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.modify_detector.setFont(font)
        self.modify_detector.setObjectName(_fromUtf8("modify_detector"))
        self.del_detector = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.del_detector.setFont(font)
        self.del_detector.setObjectName(_fromUtf8("del_detector"))
        self.action_3 = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.action_3.setFont(font)
        self.action_3.setObjectName(_fromUtf8("action_3"))
        self.action_5 = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.action_5.setFont(font)
        self.action_5.setObjectName(_fromUtf8("action_5"))
        self.action_9 = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.action_9.setFont(font)
        self.action_9.setObjectName(_fromUtf8("action_9"))
        self.fullScreen = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.fullScreen.setFont(font)
        self.fullScreen.setObjectName(_fromUtf8("fullScreen"))
        self.showNormal = QtGui.QAction(MainWindow)
        self.showNormal.setObjectName(_fromUtf8("showNormal"))

        self.retranslateUi(MainWindow)
        self.tabWidget1.setCurrentIndex(0)
        self.tabWidget3.setCurrentIndex(0)
        self.tabWidget2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "监控报警系统", None))
        self.tableWidget1.setSortingEnabled(False)
        item = self.tableWidget1.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "区域名称", None))
        item = self.tableWidget1.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "安装数量", None))
        item = self.tableWidget1.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "报警数量", None))
        item = self.tableWidget1.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "故障数量", None))
        item = self.tableWidget1.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "状态", None))
        item = self.tableWidget1.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "监控器编号", None))
        item = self.tableWidget1.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "安装时间", None))
        self.tabWidget1.setTabText(self.tabWidget1.indexOf(self.tab), _translate("MainWindow", "监控器列表", None))
        item = self.aftableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "监控区域", None))
        item = self.aftableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "检测器位置", None))
        item = self.aftableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "状态", None))
        item = self.aftableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "测量值", None))
        item = self.aftableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "测量物质", None))
        item = self.aftableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "报警/故障发生时间", None))
        item = self.aftableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "报警/故障恢复时间", None))
        self.tabWidget1.setTabText(self.tabWidget1.indexOf(self.tab_11), _translate("MainWindow", "检测器报警列表", None))
        item = self.wtableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "监控区域", None))
        item = self.wtableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "检测器位置", None))
        item = self.wtableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "状态", None))
        item = self.wtableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "测量值", None))
        item = self.wtableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "测量物质", None))
        item = self.wtableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "报警/故障发生时间", None))
        item = self.wtableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "报警/故障恢复时间", None))
        self.tabWidget1.setTabText(self.tabWidget1.indexOf(self.tab_2), _translate("MainWindow", "待选控制器", None))
        item = self.tableWidget_alarmrecord.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "监控区域", None))
        item = self.tableWidget_alarmrecord.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "监控器编号", None))
        item = self.tableWidget_alarmrecord.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "状态", None))
        item = self.tableWidget_alarmrecord.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "故障时间", None))
        self.label.setText(_translate("MainWindow", "时间", None))
        self.label_8.setText(_translate("MainWindow", "至", None))
        self.label_9.setText(_translate("MainWindow", "区域", None))
        self.comboBox_region.setItemText(0, _translate("MainWindow", "所有", None))
        self.queryButton.setText(_translate("MainWindow", "查询", None))
        self.export_drecord_Button.setText(_translate("MainWindow", "导出", None))
        self.comboBox_ctrller.setItemText(0, _translate("MainWindow", "所有", None))
        self.label_14.setText(_translate("MainWindow", "监控器", None))
        self.tabWidget3.setTabText(self.tabWidget3.indexOf(self.tab_4), _translate("MainWindow", "控制器故障记录", None))
        item = self.tableWidget_walarmrecord.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "监控区域", None))
        item = self.tableWidget_walarmrecord.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "监控器编号", None))
        item = self.tableWidget_walarmrecord.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "设备位置", None))
        item = self.tableWidget_walarmrecord.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "报警/故障时间", None))
        item = self.tableWidget_walarmrecord.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "设备状态", None))
        item = self.tableWidget_walarmrecord.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "设备编码", None))
        self.label_10.setText(_translate("MainWindow", "区域", None))
        self.label_11.setText(_translate("MainWindow", "至", None))
        self.wqueryButton.setText(_translate("MainWindow", "查询", None))
        self.label_12.setText(_translate("MainWindow", "时间", None))
        self.export_crecord_Button.setText(_translate("MainWindow", "导出", None))
        self.label_16.setText(_translate("MainWindow", "监控器", None))
        self.label_19.setText(_translate("MainWindow", "设备位置", None))
        self.tabWidget3.setTabText(self.tabWidget3.indexOf(self.tab_5), _translate("MainWindow", "设备报警/故障记录", None))
        self.label_3.setText(_translate("MainWindow", "时间：", None))
        self.label_27.setText(_translate("MainWindow", "监控器", None))
        item = self.tableWidget_concttrecord.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "监控器编号", None))
        item = self.tableWidget_concttrecord.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "检测器位置", None))
        item = self.tableWidget_concttrecord.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "记录时间", None))
        item = self.tableWidget_concttrecord.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "设备状态", None))
        item = self.tableWidget_concttrecord.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "测量值", None))
        item = self.tableWidget_concttrecord.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "测量物质", None))
        item = self.tableWidget_concttrecord.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "设备编码", None))
        self.queryButton_conctt.setText(_translate("MainWindow", "查询", None))
        self.comboBox_conctt_ctrller.setItemText(0, _translate("MainWindow", "所有", None))
        self.label_28.setText(_translate("MainWindow", "至", None))
        self.export_hrecord_Button.setText(_translate("MainWindow", "导出", None))
        self.comboBox_conctt_detector.setItemText(0, _translate("MainWindow", "所有", None))
        self.label_29.setText(_translate("MainWindow", "检测位置", None))
        self.tabWidget3.setTabText(self.tabWidget3.indexOf(self.tab_concentration), _translate("MainWindow", "检测器历史曲线", None))
        item = self.tableWidget2_1.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "区域名称", None))
        item = self.tableWidget2_1.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "控制器编号", None))
        item = self.tableWidget2_1.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "开通数量", None))
        item = self.tableWidget2_1.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "安装时间", None))
        item = self.tableWidget2_1.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "手机号码1", None))
        item = self.tableWidget2_1.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "手机号码2", None))
        item = self.tableWidget2_1.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "手机号码3", None))
        item = self.tableWidget2_1.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "手机号码4", None))
        self.addButton.setText(_translate("MainWindow", "增  加", None))
        self.delButton.setText(_translate("MainWindow", "删  除", None))
        self.editButton.setText(_translate("MainWindow", "编  辑", None))
        self.lineEdit.setText(_translate("MainWindow", "1", None))
        self.exportdtctButton.setText(_translate("MainWindow", "导  出", None))
        self.importdtctButton.setText(_translate("MainWindow", "导  入", None))
        self.tabWidget2.setTabText(self.tabWidget2.indexOf(self.tab_7), _translate("MainWindow", "控制器设置", None))
        item = self.winfotableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "区域名称", None))
        item = self.winfotableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "地址编码", None))
        item = self.winfotableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "安装位置", None))
        item = self.winfotableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "小数点位置", None))
        item = self.winfotableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "测量物质", None))
        item = self.winfotableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "计量单位", None))
        item = self.winfotableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "安装时间", None))
        self.wlineEdit.setText(_translate("MainWindow", "1", None))
        self.waddButton.setText(_translate("MainWindow", "增  加", None))
        self.wdelButton.setText(_translate("MainWindow", "删  除", None))
        self.weditButton.setText(_translate("MainWindow", "编  辑", None))
        self.exportexctrlButton.setText(_translate("MainWindow", "导  出", None))
        self.importexctrlButton.setText(_translate("MainWindow", "导  入", None))
        self.readButton.setText(_translate("MainWindow", "读取", None))
        self.tabWidget2.setTabText(self.tabWidget2.indexOf(self.tab_8), _translate("MainWindow", "待选控制器", None))
        self.groupBox.setTitle(_translate("MainWindow", "串口设置", None))
        self.label_13.setText(_translate("MainWindow", "采集串口号:", None))
        self.comcomboBox.setItemText(0, _translate("MainWindow", "COM1", None))
        self.comcomboBox.setItemText(1, _translate("MainWindow", "COM2", None))
        self.comcomboBox.setItemText(2, _translate("MainWindow", "COM3", None))
        self.comcomboBox.setItemText(3, _translate("MainWindow", "COM4", None))
        self.serialButton.setText(_translate("MainWindow", "确定", None))
        self.smscomboBox.setItemText(0, _translate("MainWindow", "COM2", None))
        self.smscomboBox.setItemText(1, _translate("MainWindow", "COM1", None))
        self.smscomboBox.setItemText(2, _translate("MainWindow", "COM3", None))
        self.smscomboBox.setItemText(3, _translate("MainWindow", "COM4", None))
        self.label_15.setText(_translate("MainWindow", "SMS串口号:", None))
        self.smscomButton.setText(_translate("MainWindow", "确定", None))
        self.output_label.setText(_translate("MainWindow", "监听输出:", None))
        self.outputcomButton.setText(_translate("MainWindow", "确定", None))
        self.outputcomboBox.setItemText(0, _translate("MainWindow", "COM3", None))
        self.outputcomboBox.setItemText(1, _translate("MainWindow", "COM1", None))
        self.outputcomboBox.setItemText(2, _translate("MainWindow", "COM2", None))
        self.outputcomboBox.setItemText(3, _translate("MainWindow", "COM4", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "用户信息设置", None))
        self.label_17.setText(_translate("MainWindow", "用 户 名 称:", None))
        self.label_18.setText(_translate("MainWindow", "采集间隔", None))
        self.smssaveButton.setText(_translate("MainWindow", "保存", None))
        self.smseditButton.setText(_translate("MainWindow", "编辑", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "密码设置", None))
        self.label_39.setText(_translate("MainWindow", "当 前 密 码：", None))
        self.label_40.setText(_translate("MainWindow", "修 改 密 码：", None))
        self.label_41.setText(_translate("MainWindow", "确 认 密 码：", None))
        self.confirm_modify_Button.setText(_translate("MainWindow", "保存", None))
        self.modify_psw_Button.setText(_translate("MainWindow", "编辑", None))
        self.headlabel.setText(_translate("MainWindow", "DCS　监　控　软　件", None))
        self.label_4.setText(_translate("MainWindow", "信　息　提　示", None))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.mainuiButton.setText(_translate("MainWindow", "设备监控", None))
        self.alarmquButton.setText(_translate("MainWindow", "数据查询", None))
        self.exitButton.setText(_translate("MainWindow", "退出系统", None))
        self.deinfoButton.setText(_translate("MainWindow", "工程模式", None))
        self.controlButton.setText(_translate("MainWindow", "系统设置", None))
        self.port_led_Button.setText(_translate("MainWindow", "串口", None))
        self.fault_led_Button.setText(_translate("MainWindow", "故障", None))
        self.alarm_led_Button.setText(_translate("MainWindow", "报警", None))
        self.startButton.setText(_translate("MainWindow", "开始运行", None))
        self.resetButton.setText(_translate("MainWindow", "系统复位", None))
        self.bequietButton.setText(_translate("MainWindow", "消除声音", None))
        self.shield_led_Button.setText(_translate("MainWindow", "屏蔽", None))
        self.comset.setText(_translate("MainWindow", "通信设置", None))
        self.action_2.setText(_translate("MainWindow", "系统信息", None))
        self.exit.setText(_translate("MainWindow", "退出", None))
        self.action_7.setText(_translate("MainWindow", "系统信息", None))
        self.action_8.setText(_translate("MainWindow", "报警记录", None))
        self.add_detector.setText(_translate("MainWindow", "添加探测器", None))
        self.modify_detector.setText(_translate("MainWindow", "修改探测器", None))
        self.del_detector.setText(_translate("MainWindow", "删除探测器", None))
        self.action_3.setText(_translate("MainWindow", "添加外控器", None))
        self.action_5.setText(_translate("MainWindow", "修改外控器", None))
        self.action_9.setText(_translate("MainWindow", "删除外控器", None))
        self.fullScreen.setText(_translate("MainWindow", "全屏", None))
        self.showNormal.setText(_translate("MainWindow", "正常显示", None))

